# This Makefile is for the libxml-enno extension to perl.
#
# It was generated automatically by MakeMaker version
# 6.30 (Revision: Revision: 4535 ) from the contents of
# Makefile.PL. Don't edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: ()
#
#   MakeMaker Parameters:

#     EXE_FILES => [q[bin/xql.pl]]
#     NAME => q[libxml-enno]
#     PREREQ_PM => { XML::Parser::PerlSAX=>q[0.07], LWP::UserAgent=>q[0], Date::Manip=>q[5.33], Parse::Yapp=>q[0], XML::Parser=>q[2.19] }
#     VERSION_FROM => q[Makefile.PL]
#     dist => { COMPRESS=>q[gzip], SUFFIX=>q[.gz] }

# --- MakeMaker post_initialize section:


# --- MakeMaker const_config section:

# These definitions are from config.sh (via /usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi/Config.pm)

# They may have been overridden via Makefile.PL or on the command line
AR = ar
CC = gcc
CCCDLFLAGS = -fPIC
CCDLFLAGS = -Wl,-E -Wl,-rpath,/usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi/CORE
DLEXT = so
DLSRC = dl_dlopen.xs
LD = gcc
LDDLFLAGS = -shared -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic
LDFLAGS = 
LIBC = 
LIB_EXT = .a
OBJ_EXT = .o
OSNAME = linux
OSVERS = 2.6.18-53.el5
RANLIB = :
SITELIBEXP = /usr/lib/perl5/site_perl/5.8.8
SITEARCHEXP = /usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi
SO = so
EXE_EXT = 
FULL_AR = /usr/bin/ar
VENDORARCHEXP = /usr/lib64/perl5/vendor_perl/5.8.8/x86_64-linux-thread-multi
VENDORLIBEXP = /usr/lib/perl5/vendor_perl/5.8.8


# --- MakeMaker constants section:
AR_STATIC_ARGS = cr
DIRFILESEP = /
DFSEP = $(DIRFILESEP)
NAME = libxml-enno
NAME_SYM = libxml_enno
VERSION = 1.02
VERSION_MACRO = VERSION
VERSION_SYM = 1_02
DEFINE_VERSION = -D$(VERSION_MACRO)=\"$(VERSION)\"
XS_VERSION = 1.02
XS_VERSION_MACRO = XS_VERSION
XS_DEFINE_VERSION = -D$(XS_VERSION_MACRO)=\"$(XS_VERSION)\"
INST_ARCHLIB = blib/arch
INST_SCRIPT = blib/script
INST_BIN = blib/bin
INST_LIB = blib/lib
INST_MAN1DIR = blib/man1
INST_MAN3DIR = blib/man3
MAN1EXT = 1
MAN3EXT = 3pm
INSTALLDIRS = site
DESTDIR = 
PREFIX = $(SITEPREFIX)
PERLPREFIX = /usr
SITEPREFIX = /usr
VENDORPREFIX = /usr
INSTALLPRIVLIB = /usr/lib/perl5/5.8.8
DESTINSTALLPRIVLIB = $(DESTDIR)$(INSTALLPRIVLIB)
INSTALLSITELIB = /usr/lib/perl5/site_perl/5.8.8
DESTINSTALLSITELIB = $(DESTDIR)$(INSTALLSITELIB)
INSTALLVENDORLIB = /usr/lib/perl5/vendor_perl/5.8.8
DESTINSTALLVENDORLIB = $(DESTDIR)$(INSTALLVENDORLIB)
INSTALLARCHLIB = /usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi
DESTINSTALLARCHLIB = $(DESTDIR)$(INSTALLARCHLIB)
INSTALLSITEARCH = /usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi
DESTINSTALLSITEARCH = $(DESTDIR)$(INSTALLSITEARCH)
INSTALLVENDORARCH = /usr/lib64/perl5/vendor_perl/5.8.8/x86_64-linux-thread-multi
DESTINSTALLVENDORARCH = $(DESTDIR)$(INSTALLVENDORARCH)
INSTALLBIN = /usr/bin
DESTINSTALLBIN = $(DESTDIR)$(INSTALLBIN)
INSTALLSITEBIN = /usr/bin
DESTINSTALLSITEBIN = $(DESTDIR)$(INSTALLSITEBIN)
INSTALLVENDORBIN = /usr/bin
DESTINSTALLVENDORBIN = $(DESTDIR)$(INSTALLVENDORBIN)
INSTALLSCRIPT = /usr/bin
DESTINSTALLSCRIPT = $(DESTDIR)$(INSTALLSCRIPT)
INSTALLMAN1DIR = /usr/share/man/man1
DESTINSTALLMAN1DIR = $(DESTDIR)$(INSTALLMAN1DIR)
INSTALLSITEMAN1DIR = /usr/share/man/man1
DESTINSTALLSITEMAN1DIR = $(DESTDIR)$(INSTALLSITEMAN1DIR)
INSTALLVENDORMAN1DIR = /usr/share/man/man1
DESTINSTALLVENDORMAN1DIR = $(DESTDIR)$(INSTALLVENDORMAN1DIR)
INSTALLMAN3DIR = /usr/share/man/man3
DESTINSTALLMAN3DIR = $(DESTDIR)$(INSTALLMAN3DIR)
INSTALLSITEMAN3DIR = /usr/share/man/man3
DESTINSTALLSITEMAN3DIR = $(DESTDIR)$(INSTALLSITEMAN3DIR)
INSTALLVENDORMAN3DIR = /usr/share/man/man3
DESTINSTALLVENDORMAN3DIR = $(DESTDIR)$(INSTALLVENDORMAN3DIR)
PERL_LIB = /usr/lib/perl5/5.8.8
PERL_ARCHLIB = /usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi
LIBPERL_A = libperl.a
FIRST_MAKEFILE = Makefile
MAKEFILE_OLD = Makefile.old
MAKE_APERL_FILE = Makefile.aperl
PERLMAINCC = $(CC)
PERL_INC = /usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi/CORE
PERL = /usr/bin/perl
FULLPERL = /usr/bin/perl
ABSPERL = $(PERL)
PERLRUN = $(PERL)
FULLPERLRUN = $(FULLPERL)
ABSPERLRUN = $(ABSPERL)
PERLRUNINST = $(PERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
FULLPERLRUNINST = $(FULLPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
ABSPERLRUNINST = $(ABSPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
PERL_CORE = 0
PERM_RW = 644
PERM_RWX = 755

MAKEMAKER   = /usr/lib/perl5/5.8.8/ExtUtils/MakeMaker.pm
MM_VERSION  = 6.30
MM_REVISION = Revision: 4535 

# FULLEXT = Pathname for extension directory (eg Foo/Bar/Oracle).
# BASEEXT = Basename part of FULLEXT. May be just equal FULLEXT. (eg Oracle)
# PARENT_NAME = NAME without BASEEXT and no trailing :: (eg Foo::Bar)
# DLBASE  = Basename part of dynamic library. May be just equal BASEEXT.
FULLEXT = libxml-enno
BASEEXT = enno
PARENT_NAME = 
DLBASE = $(BASEEXT)
VERSION_FROM = Makefile.PL
OBJECT = 
LDFROM = $(OBJECT)
LINKTYPE = dynamic
BOOTDEP = 

# Handy lists of source code files:
XS_FILES = 
C_FILES  = 
O_FILES  = 
H_FILES  = 
MAN1PODS = 
MAN3PODS = lib/XML/Checker.pm \
	lib/XML/Checker/Parser.pm \
	lib/XML/DOM.pm \
	lib/XML/DOM/AttDef.pod \
	lib/XML/DOM/AttlistDecl.pod \
	lib/XML/DOM/Attr.pod \
	lib/XML/DOM/CDATASection.pod \
	lib/XML/DOM/CharacterData.pod \
	lib/XML/DOM/Comment.pod \
	lib/XML/DOM/DOMImplementation.pod \
	lib/XML/DOM/Document.pod \
	lib/XML/DOM/DocumentFragment.pod \
	lib/XML/DOM/DocumentType.pod \
	lib/XML/DOM/Element.pod \
	lib/XML/DOM/ElementDecl.pod \
	lib/XML/DOM/Entity.pod \
	lib/XML/DOM/EntityReference.pod \
	lib/XML/DOM/NamedNodeMap.pod \
	lib/XML/DOM/Node.pod \
	lib/XML/DOM/NodeList.pod \
	lib/XML/DOM/Notation.pod \
	lib/XML/DOM/Parser.pod \
	lib/XML/DOM/PerlSAX.pm \
	lib/XML/DOM/ProcessingInstruction.pod \
	lib/XML/DOM/Text.pod \
	lib/XML/DOM/ValParser.pm \
	lib/XML/DOM/XMLDecl.pod \
	lib/XML/Filter/DetectWS.pm \
	lib/XML/Filter/Reindent.pm \
	lib/XML/Filter/SAXT.pm \
	lib/XML/Handler/BuildDOM.pm \
	lib/XML/Handler/Composer.pm \
	lib/XML/Handler/PrintEvents.pm \
	lib/XML/RegExp.pm \
	lib/XML/UM.pm \
	lib/XML/XQL.pm \
	lib/XML/XQL/DOM.pm \
	lib/XML/XQL/Date.pm \
	lib/XML/XQL/Query.pod \
	lib/XML/XQL/Tutorial.pod

# Where is the Config information that we are using/depend on
CONFIGDEP = $(PERL_ARCHLIB)$(DFSEP)Config.pm $(PERL_INC)$(DFSEP)config.h

# Where to build things
INST_LIBDIR      = $(INST_LIB)
INST_ARCHLIBDIR  = $(INST_ARCHLIB)

INST_AUTODIR     = $(INST_LIB)/auto/$(FULLEXT)
INST_ARCHAUTODIR = $(INST_ARCHLIB)/auto/$(FULLEXT)

INST_STATIC      = 
INST_DYNAMIC     = 
INST_BOOT        = 

# Extra linker info
EXPORT_LIST        = 
PERL_ARCHIVE       = 
PERL_ARCHIVE_AFTER = 


TO_INST_PM = lib/XML/Checker.pm \
	lib/XML/Checker/DOM.pm \
	lib/XML/Checker/Parser.pm \
	lib/XML/DOM.pm \
	lib/XML/DOM/AttDef.pod \
	lib/XML/DOM/AttlistDecl.pod \
	lib/XML/DOM/Attr.pod \
	lib/XML/DOM/CDATASection.pod \
	lib/XML/DOM/CharacterData.pod \
	lib/XML/DOM/Comment.pod \
	lib/XML/DOM/DOMException.pm \
	lib/XML/DOM/DOMImplementation.pod \
	lib/XML/DOM/Document.pod \
	lib/XML/DOM/DocumentFragment.pod \
	lib/XML/DOM/DocumentType.pod \
	lib/XML/DOM/Element.pod \
	lib/XML/DOM/ElementDecl.pod \
	lib/XML/DOM/Entity.pod \
	lib/XML/DOM/EntityReference.pod \
	lib/XML/DOM/NamedNodeMap.pm \
	lib/XML/DOM/NamedNodeMap.pod \
	lib/XML/DOM/Node.pod \
	lib/XML/DOM/NodeList.pm \
	lib/XML/DOM/NodeList.pod \
	lib/XML/DOM/Notation.pod \
	lib/XML/DOM/Parser.pod \
	lib/XML/DOM/PerlSAX.pm \
	lib/XML/DOM/ProcessingInstruction.pod \
	lib/XML/DOM/Text.pod \
	lib/XML/DOM/ValParser.pm \
	lib/XML/DOM/XMLDecl.pod \
	lib/XML/Filter/DetectWS.pm \
	lib/XML/Filter/Reindent.pm \
	lib/XML/Filter/SAXT.pm \
	lib/XML/Handler/BuildDOM.pm \
	lib/XML/Handler/Composer.pm \
	lib/XML/Handler/PrintEvents.pm \
	lib/XML/RegExp.pm \
	lib/XML/UM.pm \
	lib/XML/XQL.pm \
	lib/XML/XQL/DOM.pm \
	lib/XML/XQL/Date.pm \
	lib/XML/XQL/Debug.pm \
	lib/XML/XQL/DirXQL.pm \
	lib/XML/XQL/Plus.pm \
	lib/XML/XQL/Query.pod \
	lib/XML/XQL/Strict.pm \
	lib/XML/XQL/Tutorial.pod

PM_TO_BLIB = lib/XML/DOM/DocumentType.pod \
	blib/lib/XML/DOM/DocumentType.pod \
	lib/XML/DOM.pm \
	blib/lib/XML/DOM.pm \
	lib/XML/Handler/BuildDOM.pm \
	blib/lib/XML/Handler/BuildDOM.pm \
	lib/XML/DOM/DocumentFragment.pod \
	blib/lib/XML/DOM/DocumentFragment.pod \
	lib/XML/DOM/AttlistDecl.pod \
	blib/lib/XML/DOM/AttlistDecl.pod \
	lib/XML/DOM/Notation.pod \
	blib/lib/XML/DOM/Notation.pod \
	lib/XML/DOM/Attr.pod \
	blib/lib/XML/DOM/Attr.pod \
	lib/XML/DOM/ProcessingInstruction.pod \
	blib/lib/XML/DOM/ProcessingInstruction.pod \
	lib/XML/DOM/Entity.pod \
	blib/lib/XML/DOM/Entity.pod \
	lib/XML/XQL/Query.pod \
	blib/lib/XML/XQL/Query.pod \
	lib/XML/Checker/DOM.pm \
	blib/lib/XML/Checker/DOM.pm \
	lib/XML/DOM/Document.pod \
	blib/lib/XML/DOM/Document.pod \
	lib/XML/Handler/PrintEvents.pm \
	blib/lib/XML/Handler/PrintEvents.pm \
	lib/XML/DOM/Parser.pod \
	blib/lib/XML/DOM/Parser.pod \
	lib/XML/XQL/DOM.pm \
	blib/lib/XML/XQL/DOM.pm \
	lib/XML/DOM/NodeList.pm \
	blib/lib/XML/DOM/NodeList.pm \
	lib/XML/XQL/Date.pm \
	blib/lib/XML/XQL/Date.pm \
	lib/XML/DOM/Node.pod \
	blib/lib/XML/DOM/Node.pod \
	lib/XML/DOM/ElementDecl.pod \
	blib/lib/XML/DOM/ElementDecl.pod \
	lib/XML/XQL/Tutorial.pod \
	blib/lib/XML/XQL/Tutorial.pod \
	lib/XML/Handler/Composer.pm \
	blib/lib/XML/Handler/Composer.pm \
	lib/XML/DOM/ValParser.pm \
	blib/lib/XML/DOM/ValParser.pm \
	lib/XML/DOM/EntityReference.pod \
	blib/lib/XML/DOM/EntityReference.pod \
	lib/XML/Filter/DetectWS.pm \
	blib/lib/XML/Filter/DetectWS.pm \
	lib/XML/UM.pm \
	blib/lib/XML/UM.pm \
	lib/XML/Filter/SAXT.pm \
	blib/lib/XML/Filter/SAXT.pm \
	lib/XML/DOM/CharacterData.pod \
	blib/lib/XML/DOM/CharacterData.pod \
	lib/XML/DOM/NodeList.pod \
	blib/lib/XML/DOM/NodeList.pod \
	lib/XML/RegExp.pm \
	blib/lib/XML/RegExp.pm \
	lib/XML/DOM/DOMException.pm \
	blib/lib/XML/DOM/DOMException.pm \
	lib/XML/DOM/PerlSAX.pm \
	blib/lib/XML/DOM/PerlSAX.pm \
	lib/XML/DOM/NamedNodeMap.pm \
	blib/lib/XML/DOM/NamedNodeMap.pm \
	lib/XML/Filter/Reindent.pm \
	blib/lib/XML/Filter/Reindent.pm \
	lib/XML/DOM/NamedNodeMap.pod \
	blib/lib/XML/DOM/NamedNodeMap.pod \
	lib/XML/XQL/DirXQL.pm \
	blib/lib/XML/XQL/DirXQL.pm \
	lib/XML/DOM/Comment.pod \
	blib/lib/XML/DOM/Comment.pod \
	lib/XML/DOM/Element.pod \
	blib/lib/XML/DOM/Element.pod \
	lib/XML/DOM/XMLDecl.pod \
	blib/lib/XML/DOM/XMLDecl.pod \
	lib/XML/XQL/Strict.pm \
	blib/lib/XML/XQL/Strict.pm \
	lib/XML/DOM/CDATASection.pod \
	blib/lib/XML/DOM/CDATASection.pod \
	lib/XML/XQL/Debug.pm \
	blib/lib/XML/XQL/Debug.pm \
	lib/XML/Checker/Parser.pm \
	blib/lib/XML/Checker/Parser.pm \
	lib/XML/DOM/DOMImplementation.pod \
	blib/lib/XML/DOM/DOMImplementation.pod \
	lib/XML/XQL/Plus.pm \
	blib/lib/XML/XQL/Plus.pm \
	lib/XML/XQL.pm \
	blib/lib/XML/XQL.pm \
	lib/XML/Checker.pm \
	blib/lib/XML/Checker.pm \
	lib/XML/DOM/Text.pod \
	blib/lib/XML/DOM/Text.pod \
	lib/XML/DOM/AttDef.pod \
	blib/lib/XML/DOM/AttDef.pod


# --- MakeMaker platform_constants section:
MM_Unix_VERSION = 1.50
PERL_MALLOC_DEF = -DPERL_EXTMALLOC_DEF -Dmalloc=Perl_malloc -Dfree=Perl_mfree -Drealloc=Perl_realloc -Dcalloc=Perl_calloc


# --- MakeMaker tool_autosplit section:
# Usage: $(AUTOSPLITFILE) FileToSplit AutoDirToSplitInto
AUTOSPLITFILE = $(ABSPERLRUN)  -e 'use AutoSplit;  autosplit($$ARGV[0], $$ARGV[1], 0, 1, 1)'



# --- MakeMaker tool_xsubpp section:


# --- MakeMaker tools_other section:
SHELL = /bin/sh
CHMOD = chmod
CP = cp
MV = mv
NOOP = $(SHELL) -c true
NOECHO = @
RM_F = rm -f
RM_RF = rm -rf
TEST_F = test -f
TOUCH = touch
UMASK_NULL = umask 0
DEV_NULL = > /dev/null 2>&1
MKPATH = $(ABSPERLRUN) "-MExtUtils::Command" -e mkpath
EQUALIZE_TIMESTAMP = $(ABSPERLRUN) "-MExtUtils::Command" -e eqtime
ECHO = echo
ECHO_N = echo -n
UNINST = 0
VERBINST = 0
MOD_INSTALL = $(ABSPERLRUN) -MExtUtils::Install -e 'install({@ARGV}, '\''$(VERBINST)'\'', 0, '\''$(UNINST)'\'');'
DOC_INSTALL = $(ABSPERLRUN) "-MExtUtils::Command::MM" -e perllocal_install
UNINSTALL = $(ABSPERLRUN) "-MExtUtils::Command::MM" -e uninstall
WARN_IF_OLD_PACKLIST = $(ABSPERLRUN) "-MExtUtils::Command::MM" -e warn_if_old_packlist
MACROSTART = 
MACROEND = 
USEMAKEFILE = -f
FIXIN = $(PERLRUN) "-MExtUtils::MY" -e "MY->fixin(shift)"


# --- MakeMaker makemakerdflt section:
makemakerdflt: all
	$(NOECHO) $(NOOP)


# --- MakeMaker dist section:
TAR = tar
TARFLAGS = cvf
ZIP = zip
ZIPFLAGS = -r
COMPRESS = gzip
SUFFIX = .gz
SHAR = shar
PREOP = $(NOECHO) $(NOOP)
POSTOP = $(NOECHO) $(NOOP)
TO_UNIX = $(NOECHO) $(NOOP)
CI = ci -u
RCS_LABEL = rcs -Nv$(VERSION_SYM): -q
DIST_CP = best
DIST_DEFAULT = tardist
DISTNAME = libxml-enno
DISTVNAME = libxml-enno-1.02


# --- MakeMaker macro section:


# --- MakeMaker depend section:


# --- MakeMaker cflags section:


# --- MakeMaker const_loadlibs section:


# --- MakeMaker const_cccmd section:


# --- MakeMaker post_constants section:


# --- MakeMaker pasthru section:

PASTHRU = LIBPERL_A="$(LIBPERL_A)"\
	LINKTYPE="$(LINKTYPE)"\
	PREFIX="$(PREFIX)"


# --- MakeMaker special_targets section:
.SUFFIXES : .xs .c .C .cpp .i .s .cxx .cc $(OBJ_EXT)

.PHONY: all config static dynamic test linkext manifest blibdirs clean realclean disttest distdir



# --- MakeMaker c_o section:


# --- MakeMaker xs_c section:


# --- MakeMaker xs_o section:


# --- MakeMaker top_targets section:
all :: pure_all manifypods
	$(NOECHO) $(NOOP)


pure_all :: config pm_to_blib subdirs linkext
	$(NOECHO) $(NOOP)

subdirs :: $(MYEXTLIB)
	$(NOECHO) $(NOOP)

config :: $(FIRST_MAKEFILE) blibdirs
	$(NOECHO) $(NOOP)

help :
	perldoc ExtUtils::MakeMaker


# --- MakeMaker blibdirs section:
blibdirs : $(INST_LIBDIR)$(DFSEP).exists $(INST_ARCHLIB)$(DFSEP).exists $(INST_AUTODIR)$(DFSEP).exists $(INST_ARCHAUTODIR)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists $(INST_SCRIPT)$(DFSEP).exists $(INST_MAN1DIR)$(DFSEP).exists $(INST_MAN3DIR)$(DFSEP).exists
	$(NOECHO) $(NOOP)

# Backwards compat with 6.18 through 6.25
blibdirs.ts : blibdirs
	$(NOECHO) $(NOOP)

$(INST_LIBDIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_LIBDIR)
	$(NOECHO) $(CHMOD) 755 $(INST_LIBDIR)
	$(NOECHO) $(TOUCH) $(INST_LIBDIR)$(DFSEP).exists

$(INST_ARCHLIB)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHLIB)
	$(NOECHO) $(CHMOD) 755 $(INST_ARCHLIB)
	$(NOECHO) $(TOUCH) $(INST_ARCHLIB)$(DFSEP).exists

$(INST_AUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_AUTODIR)
	$(NOECHO) $(CHMOD) 755 $(INST_AUTODIR)
	$(NOECHO) $(TOUCH) $(INST_AUTODIR)$(DFSEP).exists

$(INST_ARCHAUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHAUTODIR)
	$(NOECHO) $(CHMOD) 755 $(INST_ARCHAUTODIR)
	$(NOECHO) $(TOUCH) $(INST_ARCHAUTODIR)$(DFSEP).exists

$(INST_BIN)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_BIN)
	$(NOECHO) $(CHMOD) 755 $(INST_BIN)
	$(NOECHO) $(TOUCH) $(INST_BIN)$(DFSEP).exists

$(INST_SCRIPT)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_SCRIPT)
	$(NOECHO) $(CHMOD) 755 $(INST_SCRIPT)
	$(NOECHO) $(TOUCH) $(INST_SCRIPT)$(DFSEP).exists

$(INST_MAN1DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN1DIR)
	$(NOECHO) $(CHMOD) 755 $(INST_MAN1DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN1DIR)$(DFSEP).exists

$(INST_MAN3DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN3DIR)
	$(NOECHO) $(CHMOD) 755 $(INST_MAN3DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN3DIR)$(DFSEP).exists



# --- MakeMaker linkext section:

linkext :: $(LINKTYPE)
	$(NOECHO) $(NOOP)


# --- MakeMaker dlsyms section:


# --- MakeMaker dynamic section:

dynamic :: $(FIRST_MAKEFILE) $(INST_DYNAMIC) $(INST_BOOT)
	$(NOECHO) $(NOOP)


# --- MakeMaker dynamic_bs section:

BOOTSTRAP =


# --- MakeMaker dynamic_lib section:


# --- MakeMaker static section:

## $(INST_PM) has been moved to the all: target.
## It remains here for awhile to allow for old usage: "make static"
static :: $(FIRST_MAKEFILE) $(INST_STATIC)
	$(NOECHO) $(NOOP)


# --- MakeMaker static_lib section:


# --- MakeMaker manifypods section:

POD2MAN_EXE = $(PERLRUN) "-MExtUtils::Command::MM" -e pod2man "--"
POD2MAN = $(POD2MAN_EXE)


manifypods : pure_all  \
	lib/XML/DOM/DocumentType.pod \
	lib/XML/DOM.pm \
	lib/XML/Handler/BuildDOM.pm \
	lib/XML/DOM/DocumentFragment.pod \
	lib/XML/DOM/AttlistDecl.pod \
	lib/XML/DOM/Notation.pod \
	lib/XML/DOM/Attr.pod \
	lib/XML/DOM/ProcessingInstruction.pod \
	lib/XML/DOM/Entity.pod \
	lib/XML/XQL/Query.pod \
	lib/XML/DOM/Document.pod \
	lib/XML/Handler/PrintEvents.pm \
	lib/XML/DOM/Parser.pod \
	lib/XML/XQL/DOM.pm \
	lib/XML/XQL/Date.pm \
	lib/XML/DOM/Node.pod \
	lib/XML/DOM/ElementDecl.pod \
	lib/XML/XQL/Tutorial.pod \
	lib/XML/Handler/Composer.pm \
	lib/XML/DOM/ValParser.pm \
	lib/XML/DOM/EntityReference.pod \
	lib/XML/Filter/DetectWS.pm \
	lib/XML/UM.pm \
	lib/XML/Filter/SAXT.pm \
	lib/XML/DOM/CharacterData.pod \
	lib/XML/DOM/NodeList.pod \
	lib/XML/RegExp.pm \
	lib/XML/DOM/PerlSAX.pm \
	lib/XML/Filter/Reindent.pm \
	lib/XML/DOM/NamedNodeMap.pod \
	lib/XML/DOM/Comment.pod \
	lib/XML/DOM/Element.pod \
	lib/XML/DOM/XMLDecl.pod \
	lib/XML/DOM/CDATASection.pod \
	lib/XML/Checker/Parser.pm \
	lib/XML/DOM/DOMImplementation.pod \
	lib/XML/XQL.pm \
	lib/XML/Checker.pm \
	lib/XML/DOM/Text.pod \
	lib/XML/DOM/AttDef.pod \
	lib/XML/DOM/DocumentType.pod \
	lib/XML/DOM.pm \
	lib/XML/Handler/BuildDOM.pm \
	lib/XML/DOM/DocumentFragment.pod \
	lib/XML/DOM/AttlistDecl.pod \
	lib/XML/DOM/Notation.pod \
	lib/XML/DOM/Attr.pod \
	lib/XML/DOM/ProcessingInstruction.pod \
	lib/XML/DOM/Entity.pod \
	lib/XML/XQL/Query.pod \
	lib/XML/DOM/Document.pod \
	lib/XML/Handler/PrintEvents.pm \
	lib/XML/DOM/Parser.pod \
	lib/XML/XQL/DOM.pm \
	lib/XML/XQL/Date.pm \
	lib/XML/DOM/Node.pod \
	lib/XML/DOM/ElementDecl.pod \
	lib/XML/XQL/Tutorial.pod \
	lib/XML/Handler/Composer.pm \
	lib/XML/DOM/ValParser.pm \
	lib/XML/DOM/EntityReference.pod \
	lib/XML/Filter/DetectWS.pm \
	lib/XML/UM.pm \
	lib/XML/Filter/SAXT.pm \
	lib/XML/DOM/CharacterData.pod \
	lib/XML/DOM/NodeList.pod \
	lib/XML/RegExp.pm \
	lib/XML/DOM/PerlSAX.pm \
	lib/XML/Filter/Reindent.pm \
	lib/XML/DOM/NamedNodeMap.pod \
	lib/XML/DOM/Comment.pod \
	lib/XML/DOM/Element.pod \
	lib/XML/DOM/XMLDecl.pod \
	lib/XML/DOM/CDATASection.pod \
	lib/XML/Checker/Parser.pm \
	lib/XML/DOM/DOMImplementation.pod \
	lib/XML/XQL.pm \
	lib/XML/Checker.pm \
	lib/XML/DOM/Text.pod \
	lib/XML/DOM/AttDef.pod
	$(NOECHO) $(POD2MAN) --section=3 --perm_rw=$(PERM_RW) \
	  lib/XML/DOM/DocumentType.pod $(INST_MAN3DIR)/XML::DOM::DocumentType.$(MAN3EXT) \
	  lib/XML/DOM.pm $(INST_MAN3DIR)/XML::DOM.$(MAN3EXT) \
	  lib/XML/Handler/BuildDOM.pm $(INST_MAN3DIR)/XML::Handler::BuildDOM.$(MAN3EXT) \
	  lib/XML/DOM/DocumentFragment.pod $(INST_MAN3DIR)/XML::DOM::DocumentFragment.$(MAN3EXT) \
	  lib/XML/DOM/AttlistDecl.pod $(INST_MAN3DIR)/XML::DOM::AttlistDecl.$(MAN3EXT) \
	  lib/XML/DOM/Notation.pod $(INST_MAN3DIR)/XML::DOM::Notation.$(MAN3EXT) \
	  lib/XML/DOM/Attr.pod $(INST_MAN3DIR)/XML::DOM::Attr.$(MAN3EXT) \
	  lib/XML/DOM/ProcessingInstruction.pod $(INST_MAN3DIR)/XML::DOM::ProcessingInstruction.$(MAN3EXT) \
	  lib/XML/DOM/Entity.pod $(INST_MAN3DIR)/XML::DOM::Entity.$(MAN3EXT) \
	  lib/XML/XQL/Query.pod $(INST_MAN3DIR)/XML::XQL::Query.$(MAN3EXT) \
	  lib/XML/DOM/Document.pod $(INST_MAN3DIR)/XML::DOM::Document.$(MAN3EXT) \
	  lib/XML/Handler/PrintEvents.pm $(INST_MAN3DIR)/XML::Handler::PrintEvents.$(MAN3EXT) \
	  lib/XML/DOM/Parser.pod $(INST_MAN3DIR)/XML::DOM::Parser.$(MAN3EXT) \
	  lib/XML/XQL/DOM.pm $(INST_MAN3DIR)/XML::XQL::DOM.$(MAN3EXT) \
	  lib/XML/XQL/Date.pm $(INST_MAN3DIR)/XML::XQL::Date.$(MAN3EXT) \
	  lib/XML/DOM/Node.pod $(INST_MAN3DIR)/XML::DOM::Node.$(MAN3EXT) \
	  lib/XML/DOM/ElementDecl.pod $(INST_MAN3DIR)/XML::DOM::ElementDecl.$(MAN3EXT) \
	  lib/XML/XQL/Tutorial.pod $(INST_MAN3DIR)/XML::XQL::Tutorial.$(MAN3EXT) \
	  lib/XML/Handler/Composer.pm $(INST_MAN3DIR)/XML::Handler::Composer.$(MAN3EXT) \
	  lib/XML/DOM/ValParser.pm $(INST_MAN3DIR)/XML::DOM::ValParser.$(MAN3EXT) \
	  lib/XML/DOM/EntityReference.pod $(INST_MAN3DIR)/XML::DOM::EntityReference.$(MAN3EXT) \
	  lib/XML/Filter/DetectWS.pm $(INST_MAN3DIR)/XML::Filter::DetectWS.$(MAN3EXT) \
	  lib/XML/UM.pm $(INST_MAN3DIR)/XML::UM.$(MAN3EXT) \
	  lib/XML/Filter/SAXT.pm $(INST_MAN3DIR)/XML::Filter::SAXT.$(MAN3EXT) \
	  lib/XML/DOM/CharacterData.pod $(INST_MAN3DIR)/XML::DOM::CharacterData.$(MAN3EXT) \
	  lib/XML/DOM/NodeList.pod $(INST_MAN3DIR)/XML::DOM::NodeList.$(MAN3EXT) \
	  lib/XML/RegExp.pm $(INST_MAN3DIR)/XML::RegExp.$(MAN3EXT) \
	  lib/XML/DOM/PerlSAX.pm $(INST_MAN3DIR)/XML::DOM::PerlSAX.$(MAN3EXT) \
	  lib/XML/Filter/Reindent.pm $(INST_MAN3DIR)/XML::Filter::Reindent.$(MAN3EXT) \
	  lib/XML/DOM/NamedNodeMap.pod $(INST_MAN3DIR)/XML::DOM::NamedNodeMap.$(MAN3EXT) \
	  lib/XML/DOM/Comment.pod $(INST_MAN3DIR)/XML::DOM::Comment.$(MAN3EXT) \
	  lib/XML/DOM/Element.pod $(INST_MAN3DIR)/XML::DOM::Element.$(MAN3EXT) \
	  lib/XML/DOM/XMLDecl.pod $(INST_MAN3DIR)/XML::DOM::XMLDecl.$(MAN3EXT) \
	  lib/XML/DOM/CDATASection.pod $(INST_MAN3DIR)/XML::DOM::CDATASection.$(MAN3EXT) \
	  lib/XML/Checker/Parser.pm $(INST_MAN3DIR)/XML::Checker::Parser.$(MAN3EXT) \
	  lib/XML/DOM/DOMImplementation.pod $(INST_MAN3DIR)/XML::DOM::DOMImplementation.$(MAN3EXT) \
	  lib/XML/XQL.pm $(INST_MAN3DIR)/XML::XQL.$(MAN3EXT) \
	  lib/XML/Checker.pm $(INST_MAN3DIR)/XML::Checker.$(MAN3EXT) \
	  lib/XML/DOM/Text.pod $(INST_MAN3DIR)/XML::DOM::Text.$(MAN3EXT) \
	  lib/XML/DOM/AttDef.pod $(INST_MAN3DIR)/XML::DOM::AttDef.$(MAN3EXT) 




# --- MakeMaker processPL section:


# --- MakeMaker installbin section:

EXE_FILES = bin/xql.pl

pure_all :: $(INST_SCRIPT)/xql.pl
	$(NOECHO) $(NOOP)

realclean ::
	$(RM_F) \
	  $(INST_SCRIPT)/xql.pl 

$(INST_SCRIPT)/xql.pl : bin/xql.pl $(FIRST_MAKEFILE) $(INST_SCRIPT)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists
	$(NOECHO) $(RM_F) $(INST_SCRIPT)/xql.pl
	$(CP) bin/xql.pl $(INST_SCRIPT)/xql.pl
	$(FIXIN) $(INST_SCRIPT)/xql.pl
	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_SCRIPT)/xql.pl



# --- MakeMaker subdirs section:

# The default clean, realclean and test targets in this Makefile
# have automatically been given entries for each subdir.


subdirs ::
	$(NOECHO) cd XQLParser && $(MAKE) $(USEMAKEFILE) $(FIRST_MAKEFILE) all $(PASTHRU)


# --- MakeMaker clean_subdirs section:
clean_subdirs :
	$(ABSPERLRUN)  -e 'chdir '\''XQLParser'\'';  system '\''$(MAKE) clean'\'' if -f '\''$(FIRST_MAKEFILE)'\'';'


# --- MakeMaker clean section:

# Delete temporary files but do not touch installed files. We don't delete
# the Makefile here so a later make realclean still has a makefile to use.

clean :: clean_subdirs
	- $(RM_F) \
	  *$(LIB_EXT) core \
	  core.[0-9] $(INST_ARCHAUTODIR)/extralibs.all \
	  core.[0-9][0-9] $(BASEEXT).bso \
	  pm_to_blib.ts core.[0-9][0-9][0-9][0-9] \
	  $(BASEEXT).x $(BOOTSTRAP) \
	  perl$(EXE_EXT) tmon.out \
	  *$(OBJ_EXT) pm_to_blib \
	  $(INST_ARCHAUTODIR)/extralibs.ld blibdirs.ts \
	  core.[0-9][0-9][0-9][0-9][0-9] *perl.core \
	  core.*perl.*.? $(MAKE_APERL_FILE) \
	  $(BASEEXT).def perl \
	  core.[0-9][0-9][0-9] mon.out \
	  lib$(BASEEXT).def perl.exe \
	  perlmain.c so_locations \
	  $(BASEEXT).exp 
	- $(RM_RF) \
	  blib 
	- $(MV) $(FIRST_MAKEFILE) $(MAKEFILE_OLD) $(DEV_NULL)


# --- MakeMaker realclean_subdirs section:
realclean_subdirs :
	- $(ABSPERLRUN)  -e 'chdir '\''XQLParser'\'';  system '\''$(MAKE) $(USEMAKEFILE) $(MAKEFILE_OLD) realclean'\'' if -f '\''$(MAKEFILE_OLD)'\'';'
	- $(ABSPERLRUN)  -e 'chdir '\''XQLParser'\'';  system '\''$(MAKE) $(USEMAKEFILE) $(FIRST_MAKEFILE) realclean'\'' if -f '\''$(FIRST_MAKEFILE)'\'';'


# --- MakeMaker realclean section:
# Delete temporary files (via clean) and also delete dist files
realclean purge ::  clean realclean_subdirs
	- $(RM_F) \
	  $(MAKEFILE_OLD) $(FIRST_MAKEFILE) 
	- $(RM_RF) \
	  $(DISTVNAME) 


# --- MakeMaker metafile section:
metafile : create_distdir
	$(NOECHO) $(ECHO) Generating META.yml
	$(NOECHO) $(ECHO) '# http://module-build.sourceforge.net/META-spec.html' > META_new.yml
	$(NOECHO) $(ECHO) '#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#' >> META_new.yml
	$(NOECHO) $(ECHO) 'name:         libxml-enno' >> META_new.yml
	$(NOECHO) $(ECHO) 'version:      1.02' >> META_new.yml
	$(NOECHO) $(ECHO) 'version_from: Makefile.PL' >> META_new.yml
	$(NOECHO) $(ECHO) 'installdirs:  site' >> META_new.yml
	$(NOECHO) $(ECHO) 'requires:' >> META_new.yml
	$(NOECHO) $(ECHO) '    Date::Manip:                   5.33' >> META_new.yml
	$(NOECHO) $(ECHO) '    LWP::UserAgent:                0' >> META_new.yml
	$(NOECHO) $(ECHO) '    Parse::Yapp:                   0' >> META_new.yml
	$(NOECHO) $(ECHO) '    XML::Parser:                   2.19' >> META_new.yml
	$(NOECHO) $(ECHO) '    XML::Parser::PerlSAX:          0.07' >> META_new.yml
	$(NOECHO) $(ECHO) '' >> META_new.yml
	$(NOECHO) $(ECHO) 'distribution_type: module' >> META_new.yml
	$(NOECHO) $(ECHO) 'generated_by: ExtUtils::MakeMaker version 6.30' >> META_new.yml
	-$(NOECHO) $(MV) META_new.yml $(DISTVNAME)/META.yml


# --- MakeMaker signature section:
signature :
	cpansign -s


# --- MakeMaker dist_basics section:
distclean :: realclean distcheck
	$(NOECHO) $(NOOP)

distcheck :
	$(PERLRUN) "-MExtUtils::Manifest=fullcheck" -e fullcheck

skipcheck :
	$(PERLRUN) "-MExtUtils::Manifest=skipcheck" -e skipcheck

manifest :
	$(PERLRUN) "-MExtUtils::Manifest=mkmanifest" -e mkmanifest

veryclean : realclean
	$(RM_F) *~ *.orig */*~ */*.orig



# --- MakeMaker dist_core section:

dist : $(DIST_DEFAULT) $(FIRST_MAKEFILE)
	$(NOECHO) $(ABSPERLRUN) -l -e 'print '\''Warning: Makefile possibly out of date with $(VERSION_FROM)'\''' \
	  -e '    if -e '\''$(VERSION_FROM)'\'' and -M '\''$(VERSION_FROM)'\'' < -M '\''$(FIRST_MAKEFILE)'\'';'

tardist : $(DISTVNAME).tar$(SUFFIX)
	$(NOECHO) $(NOOP)

uutardist : $(DISTVNAME).tar$(SUFFIX)
	uuencode $(DISTVNAME).tar$(SUFFIX) $(DISTVNAME).tar$(SUFFIX) > $(DISTVNAME).tar$(SUFFIX)_uu

$(DISTVNAME).tar$(SUFFIX) : distdir
	$(PREOP)
	$(TO_UNIX)
	$(TAR) $(TARFLAGS) $(DISTVNAME).tar $(DISTVNAME)
	$(RM_RF) $(DISTVNAME)
	$(COMPRESS) $(DISTVNAME).tar
	$(POSTOP)

zipdist : $(DISTVNAME).zip
	$(NOECHO) $(NOOP)

$(DISTVNAME).zip : distdir
	$(PREOP)
	$(ZIP) $(ZIPFLAGS) $(DISTVNAME).zip $(DISTVNAME)
	$(RM_RF) $(DISTVNAME)
	$(POSTOP)

shdist : distdir
	$(PREOP)
	$(SHAR) $(DISTVNAME) > $(DISTVNAME).shar
	$(RM_RF) $(DISTVNAME)
	$(POSTOP)


# --- MakeMaker distdir section:
create_distdir :
	$(RM_RF) $(DISTVNAME)
	$(PERLRUN) "-MExtUtils::Manifest=manicopy,maniread" \
		-e "manicopy(maniread(),'$(DISTVNAME)', '$(DIST_CP)');"

distdir : create_distdir distmeta 
	$(NOECHO) $(NOOP)



# --- MakeMaker dist_test section:
disttest : distdir
	cd $(DISTVNAME) && $(ABSPERLRUN) Makefile.PL 
	cd $(DISTVNAME) && $(MAKE) $(PASTHRU)
	cd $(DISTVNAME) && $(MAKE) test $(PASTHRU)



# --- MakeMaker dist_ci section:

ci :
	$(PERLRUN) "-MExtUtils::Manifest=maniread" \
	  -e "@all = keys %{ maniread() };" \
	  -e "print(qq{Executing $(CI) @all\n}); system(qq{$(CI) @all});" \
	  -e "print(qq{Executing $(RCS_LABEL) ...\n}); system(qq{$(RCS_LABEL) @all});"


# --- MakeMaker distmeta section:
distmeta : create_distdir metafile
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'eval { maniadd({q{META.yml} => q{Module meta-data (added by MakeMaker)}}) } ' \
	  -e '    or print "Could not add META.yml to MANIFEST: $${'\''@'\''}\n"'



# --- MakeMaker distsignature section:
distsignature : create_distdir
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'eval { maniadd({q{SIGNATURE} => q{Public-key signature (added by MakeMaker)}}) } ' \
	  -e '    or print "Could not add SIGNATURE to MANIFEST: $${'\''@'\''}\n"'
	$(NOECHO) cd $(DISTVNAME) && $(TOUCH) SIGNATURE
	cd $(DISTVNAME) && cpansign -s



# --- MakeMaker install section:

install :: all pure_install doc_install
	$(NOECHO) $(NOOP)

install_perl :: all pure_perl_install doc_perl_install
	$(NOECHO) $(NOOP)

install_site :: all pure_site_install doc_site_install
	$(NOECHO) $(NOOP)

install_vendor :: all pure_vendor_install doc_vendor_install
	$(NOECHO) $(NOOP)

pure_install :: pure_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

doc_install :: doc_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

pure__install : pure_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

doc__install : doc_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

pure_perl_install ::
	$(NOECHO) $(MOD_INSTALL) \
		read $(PERL_ARCHLIB)/auto/$(FULLEXT)/.packlist \
		write $(DESTINSTALLARCHLIB)/auto/$(FULLEXT)/.packlist \
		$(INST_LIB) $(DESTINSTALLPRIVLIB) \
		$(INST_ARCHLIB) $(DESTINSTALLARCHLIB) \
		$(INST_BIN) $(DESTINSTALLBIN) \
		$(INST_SCRIPT) $(DESTINSTALLSCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLMAN3DIR)
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		$(SITEARCHEXP)/auto/$(FULLEXT)


pure_site_install ::
	$(NOECHO) $(MOD_INSTALL) \
		read $(SITEARCHEXP)/auto/$(FULLEXT)/.packlist \
		write $(DESTINSTALLSITEARCH)/auto/$(FULLEXT)/.packlist \
		$(INST_LIB) $(DESTINSTALLSITELIB) \
		$(INST_ARCHLIB) $(DESTINSTALLSITEARCH) \
		$(INST_BIN) $(DESTINSTALLSITEBIN) \
		$(INST_SCRIPT) $(DESTINSTALLSCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLSITEMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLSITEMAN3DIR)
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		$(PERL_ARCHLIB)/auto/$(FULLEXT)

pure_vendor_install ::
	$(NOECHO) $(MOD_INSTALL) \
		read $(VENDORARCHEXP)/auto/$(FULLEXT)/.packlist \
		write $(DESTINSTALLVENDORARCH)/auto/$(FULLEXT)/.packlist \
		$(INST_LIB) $(DESTINSTALLVENDORLIB) \
		$(INST_ARCHLIB) $(DESTINSTALLVENDORARCH) \
		$(INST_BIN) $(DESTINSTALLVENDORBIN) \
		$(INST_SCRIPT) $(DESTINSTALLSCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLVENDORMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLVENDORMAN3DIR)

doc_perl_install ::
	$(NOECHO) $(ECHO) Appending installation info to $(DESTINSTALLARCHLIB)/perllocal.pod
	-$(NOECHO) $(MKPATH) $(DESTINSTALLARCHLIB)
	-$(NOECHO) $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLPRIVLIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> $(DESTINSTALLARCHLIB)/perllocal.pod

doc_site_install ::
	$(NOECHO) $(ECHO) Appending installation info to $(DESTINSTALLARCHLIB)/perllocal.pod
	-$(NOECHO) $(MKPATH) $(DESTINSTALLARCHLIB)
	-$(NOECHO) $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLSITELIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> $(DESTINSTALLARCHLIB)/perllocal.pod

doc_vendor_install ::
	$(NOECHO) $(ECHO) Appending installation info to $(DESTINSTALLARCHLIB)/perllocal.pod
	-$(NOECHO) $(MKPATH) $(DESTINSTALLARCHLIB)
	-$(NOECHO) $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLVENDORLIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> $(DESTINSTALLARCHLIB)/perllocal.pod


uninstall :: uninstall_from_$(INSTALLDIRS)dirs
	$(NOECHO) $(NOOP)

uninstall_from_perldirs ::
	$(NOECHO) $(UNINSTALL) $(PERL_ARCHLIB)/auto/$(FULLEXT)/.packlist

uninstall_from_sitedirs ::
	$(NOECHO) $(UNINSTALL) $(SITEARCHEXP)/auto/$(FULLEXT)/.packlist

uninstall_from_vendordirs ::
	$(NOECHO) $(UNINSTALL) $(VENDORARCHEXP)/auto/$(FULLEXT)/.packlist


# --- MakeMaker force section:
# Phony target to force checking subdirectories.
FORCE:
	$(NOECHO) $(NOOP)


# --- MakeMaker perldepend section:


# --- MakeMaker makefile section:
# We take a very conservative approach here, but it's worth it.
# We move Makefile to Makefile.old here to avoid gnu make looping.
$(FIRST_MAKEFILE) : Makefile.PL $(CONFIGDEP)
	$(NOECHO) $(ECHO) "Makefile out-of-date with respect to $?"
	$(NOECHO) $(ECHO) "Cleaning current config before rebuilding Makefile..."
	-$(NOECHO) $(RM_F) $(MAKEFILE_OLD)
	-$(NOECHO) $(MV)   $(FIRST_MAKEFILE) $(MAKEFILE_OLD)
	- $(MAKE) $(USEMAKEFILE) $(MAKEFILE_OLD) clean $(DEV_NULL)
	$(PERLRUN) Makefile.PL 
	$(NOECHO) $(ECHO) "==> Your Makefile has been rebuilt. <=="
	$(NOECHO) $(ECHO) "==> Please rerun the $(MAKE) command.  <=="
	false



# --- MakeMaker staticmake section:

# --- MakeMaker makeaperl section ---
MAP_TARGET    = perl
FULLPERL      = /usr/bin/perl

$(MAP_TARGET) :: static $(MAKE_APERL_FILE)
	$(MAKE) $(USEMAKEFILE) $(MAKE_APERL_FILE) $@

$(MAKE_APERL_FILE) : $(FIRST_MAKEFILE) pm_to_blib
	$(NOECHO) $(ECHO) Writing \"$(MAKE_APERL_FILE)\" for this $(MAP_TARGET)
	$(NOECHO) $(PERLRUNINST) \
		Makefile.PL DIR=XQLParser \
		MAKEFILE=$(MAKE_APERL_FILE) LINKTYPE=static \
		MAKEAPERL=1 NORECURS=1 CCCDLFLAGS=


# --- MakeMaker test section:

TEST_VERBOSE=0
TEST_TYPE=test_$(LINKTYPE)
TEST_FILE = test.pl
TEST_FILES = t/*.t
TESTDB_SW = -d

testdb :: testdb_$(LINKTYPE)

test :: $(TEST_TYPE)
	$(NOECHO) $(ABSPERLRUN)  -e 'chdir '\''XQLParser'\'';  ' \
	  -e 'system '\''$(MAKE) test $(PASTHRU)'\'' ' \
	  -e '    if -f '\''$(FIRST_MAKEFILE)'\'';'

test_dynamic :: pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) "-MExtUtils::Command::MM" "-e" "test_harness($(TEST_VERBOSE), '$(INST_LIB)', '$(INST_ARCHLIB)')" $(TEST_FILES)

testdb_dynamic :: pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) $(TESTDB_SW) "-I$(INST_LIB)" "-I$(INST_ARCHLIB)" $(TEST_FILE)

test_ : test_dynamic

test_static :: test_dynamic
testdb_static :: testdb_dynamic


# --- MakeMaker ppd section:
# Creates a PPD (Perl Package Description) for a binary distribution.
ppd:
	$(NOECHO) $(ECHO) '<SOFTPKG NAME="$(DISTNAME)" VERSION="1,02,0,0">' > $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <TITLE>$(DISTNAME)</TITLE>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <ABSTRACT></ABSTRACT>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <AUTHOR></AUTHOR>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <IMPLEMENTATION>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <DEPENDENCY NAME="Date-Manip" VERSION="5,33,0,0" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <DEPENDENCY NAME="LWP-UserAgent" VERSION="0,0,0,0" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <DEPENDENCY NAME="Parse-Yapp" VERSION="0,0,0,0" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <DEPENDENCY NAME="XML-Parser" VERSION="2,19,0,0" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <DEPENDENCY NAME="XML-Parser-PerlSAX" VERSION="0,07,0,0" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <OS NAME="$(OSNAME)" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <ARCHITECTURE NAME="x86_64-linux-thread-multi" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <CODEBASE HREF="" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    </IMPLEMENTATION>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '</SOFTPKG>' >> $(DISTNAME).ppd


# --- MakeMaker pm_to_blib section:

pm_to_blib : $(TO_INST_PM)
	$(NOECHO) $(ABSPERLRUN) -MExtUtils::Install -e 'pm_to_blib({@ARGV}, '\''$(INST_LIB)/auto'\'', '\''$(PM_FILTER)'\'')' \
	  lib/XML/DOM/DocumentType.pod blib/lib/XML/DOM/DocumentType.pod \
	  lib/XML/DOM.pm blib/lib/XML/DOM.pm \
	  lib/XML/Handler/BuildDOM.pm blib/lib/XML/Handler/BuildDOM.pm \
	  lib/XML/DOM/DocumentFragment.pod blib/lib/XML/DOM/DocumentFragment.pod \
	  lib/XML/DOM/AttlistDecl.pod blib/lib/XML/DOM/AttlistDecl.pod \
	  lib/XML/DOM/Notation.pod blib/lib/XML/DOM/Notation.pod \
	  lib/XML/DOM/Attr.pod blib/lib/XML/DOM/Attr.pod \
	  lib/XML/DOM/ProcessingInstruction.pod blib/lib/XML/DOM/ProcessingInstruction.pod \
	  lib/XML/DOM/Entity.pod blib/lib/XML/DOM/Entity.pod \
	  lib/XML/XQL/Query.pod blib/lib/XML/XQL/Query.pod \
	  lib/XML/Checker/DOM.pm blib/lib/XML/Checker/DOM.pm \
	  lib/XML/DOM/Document.pod blib/lib/XML/DOM/Document.pod \
	  lib/XML/Handler/PrintEvents.pm blib/lib/XML/Handler/PrintEvents.pm \
	  lib/XML/DOM/Parser.pod blib/lib/XML/DOM/Parser.pod \
	  lib/XML/XQL/DOM.pm blib/lib/XML/XQL/DOM.pm \
	  lib/XML/DOM/NodeList.pm blib/lib/XML/DOM/NodeList.pm \
	  lib/XML/XQL/Date.pm blib/lib/XML/XQL/Date.pm \
	  lib/XML/DOM/Node.pod blib/lib/XML/DOM/Node.pod \
	  lib/XML/DOM/ElementDecl.pod blib/lib/XML/DOM/ElementDecl.pod \
	  lib/XML/XQL/Tutorial.pod blib/lib/XML/XQL/Tutorial.pod \
	  lib/XML/Handler/Composer.pm blib/lib/XML/Handler/Composer.pm \
	  lib/XML/DOM/ValParser.pm blib/lib/XML/DOM/ValParser.pm \
	  lib/XML/DOM/EntityReference.pod blib/lib/XML/DOM/EntityReference.pod \
	  lib/XML/Filter/DetectWS.pm blib/lib/XML/Filter/DetectWS.pm \
	  lib/XML/UM.pm blib/lib/XML/UM.pm \
	  lib/XML/Filter/SAXT.pm blib/lib/XML/Filter/SAXT.pm \
	  lib/XML/DOM/CharacterData.pod blib/lib/XML/DOM/CharacterData.pod \
	  lib/XML/DOM/NodeList.pod blib/lib/XML/DOM/NodeList.pod \
	  lib/XML/RegExp.pm blib/lib/XML/RegExp.pm \
	  lib/XML/DOM/DOMException.pm blib/lib/XML/DOM/DOMException.pm \
	  lib/XML/DOM/PerlSAX.pm blib/lib/XML/DOM/PerlSAX.pm \
	  lib/XML/DOM/NamedNodeMap.pm blib/lib/XML/DOM/NamedNodeMap.pm \
	  lib/XML/Filter/Reindent.pm blib/lib/XML/Filter/Reindent.pm \
	  lib/XML/DOM/NamedNodeMap.pod blib/lib/XML/DOM/NamedNodeMap.pod \
	  lib/XML/XQL/DirXQL.pm blib/lib/XML/XQL/DirXQL.pm \
	  lib/XML/DOM/Comment.pod blib/lib/XML/DOM/Comment.pod \
	  lib/XML/DOM/Element.pod blib/lib/XML/DOM/Element.pod \
	  lib/XML/DOM/XMLDecl.pod blib/lib/XML/DOM/XMLDecl.pod \
	  lib/XML/XQL/Strict.pm blib/lib/XML/XQL/Strict.pm \
	  lib/XML/DOM/CDATASection.pod blib/lib/XML/DOM/CDATASection.pod \
	  lib/XML/XQL/Debug.pm blib/lib/XML/XQL/Debug.pm \
	  lib/XML/Checker/Parser.pm blib/lib/XML/Checker/Parser.pm \
	  lib/XML/DOM/DOMImplementation.pod blib/lib/XML/DOM/DOMImplementation.pod \
	  lib/XML/XQL/Plus.pm blib/lib/XML/XQL/Plus.pm \
	  lib/XML/XQL.pm blib/lib/XML/XQL.pm \
	  lib/XML/Checker.pm blib/lib/XML/Checker.pm \
	  lib/XML/DOM/Text.pod blib/lib/XML/DOM/Text.pod \
	  lib/XML/DOM/AttDef.pod blib/lib/XML/DOM/AttDef.pod 
	$(NOECHO) $(TOUCH) pm_to_blib


# --- MakeMaker selfdocument section:


# --- MakeMaker postamble section:


# End.
